version: "2"
volumes:
  mobius-data:
  mobius-licence:
  mongodb:

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80

  mobius:
    image: ghcr.io/mobiusflow/balena_up_mobiusflow-v2-le:2.0.0-beta.1_2.0.0-beta.1
    privileged: true
    restart: always
    ports:
      - 8080:80
      - 443:443
      - 502:502
      - 1883:1883
      - 4840:4840
      - 8883:8883
      - 9081:9081
      - 10502:10502
      - 10001:10001
      - 30815:30815
      - 30883:30883
    volumes:
      - mobius-data:/data
      - mobius-licence:/.licence
    labels:
      io.resin.features.supervisor-api: "1"

  node-red:
    image: ghcr.io/mobiusflow/node-red:0.0.12
    container_name: node-red
    privileged: false
    restart: always
    volumes:
      - node-red-assets:/assets
      - mobius-data/.node-red:/data

  manage:
    image: ghcr.io/mobiusflow/balena_up_manage-v2:2.0.0-beta.1
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - mobius-data:/data
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"

  mongodb:
    image: bitnami/mongodb:4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=r5DybE57qug3WaHebeUy2bAvvVhKXUWHD
      - MONGODB_USERNAME=mobius
      - MONGODB_PASSWORD=RmzsXQYReLHaCS5wWGjAPjtJ7VnTw4qL
      - MONGODB_DATABASE=mobius
    volumes:
      - mongodb:/bitnami/mongodb
