version: "2"
volumes:
  resin-data:
  mobius-licence:
  mongodb:

services:
  mobius:
    image: ghcr.io/mobiusflow/balena_up_mobiusflow-le:1.19.0-beta.9_1.19.0-beta.21
    privileged: true
    restart: always
    ports:
      - 8080:80
      - 443:443
      - 502:502
      - 8443:8443
      - 1883:1883
      - 4840:4840
      - 8883:8883
      - 10502:10502
      - 10001:10001
      - 30815:30815
      - 30883:30883
    volumes:
      - resin-data:/data
      - mobius-licence:/.licence
    labels:
      io.resin.features.supervisor-api: "1"

  nginx:
    build: ./nginx
    container_name: nginx
    privileged: false
    restart: always
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  manage:
    image: ghcr.io/mobiusflow/balena_up_manage:1.17.0
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - resin-data:/data
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"

  mongodb:
    image: bitnami/mongodb:4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=r5DybE57qug3WaHebeUy2bAvvVhKXUWHD
      - MONGODB_USERNAME=mobius
      - MONGODB_PASSWORD=RmzsXQYReLHaCS5wWGjAPjtJ7VnTw4qL
      - MONGODB_DATABASE=mobius
    volumes:
      - mongodb:/bitnami/mongodb
    logging:
      driver: none