version: "2"
volumes:
  resin-data:
  mobius-licence:
  mongodb:

networks:
  frontend:
  backend:

services:
  mobius:
    image: ghcr.io/mobiusflow/balena_up_mobiusflow-le:1.19.0-beta.8_1.19.0-beta.21
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
      - mobius-licence:/.licence
    networks:
      - backend
    labels:
      io.resin.features.supervisor-api: "1"

  nginx:
    image: ghcr.io/mobiusflow/nginx-cloud:1.2.2-balena-3
    container_name: nginx
    privileged: false
    restart: always
    # environment:
    #   - NGINX_UI_CONTAINER=mobius
    ports:
      - 1880:1880
      - 8443:8443
      - 1883:1883
      - 30814:30815
      - 30817:30817
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  manage:
    image: ghcr.io/mobiusflow/balena_up_manage:1.17.0
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - resin-data:/data
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"

  mongodb:
    image: bitnami/mongodb:4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=r5DybE57qug3WaHebeUy2bAvvVhKXUWHD
      - MONGODB_USERNAME=mobius
      - MONGODB_PASSWORD=RmzsXQYReLHaCS5wWGjAPjtJ7VnTw4qL
      - MONGODB_DATABASE=mobius
    volumes:
      - mongodb:/bitnami/mongodb
    networks:
      - backend
    logging:
      driver: none