FROM chirpstack/chirpstack-gateway-bridge:4

RUN mkdir -p /etc/chirpstack-gateway-bridge
COPY ./configuration/chirpstack-gateway-bridge.toml /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
